// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        int32
	Name      string
	Logo      pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type WorkOrder struct {
	ID         int32
	CustomerID int32
	Status     string
	Type       string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
